###
#
# This workflow file is deployed into this repository via the "Sync PHP Unit Organization File" workflow
#
# Direct edits to this file are at risk of being overwritten by the next sync. All edits should be made
# to the source file.
#
# @see Sync workflow {@link https://github.com/caseproof/.github/workflows/workflow-phpunit-sync.yml}
# @see Workflow template {@link https://github.com/caseproof/.github/blob/main/.github/workflow-templates/phpunit.yml}
#
###
name: PHPUnit Integration Tests

on:
  pull_request:
  workflow_dispatch:
  # At 00:00 on Sunday.
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  PHP_VERSIONS: ${{ vars.PHP_VERSIONS }}
  WP_VERSIONS: ${{ vars.WP_VERSIONS }}

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    if: ${{ fromJson(vars.WP_VERSIONS)[0] }}
    steps:
      - name: Prepare Matrix
        run: |
          echo WP_VERSIONS="${WP_VERSIONS%]*}, nightly" >> $GITHUB_ENV

  tests:
    needs: matrix_prep
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.wp == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        wp: ${{ fromJson(env.WP_VERSIONS) }}      
        php: ${{ fromJson(env.PHP_VERSIONS) }}

    name: PHP ${{ matrix.php }} (with WP ${{ matrix.wp }})

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{secrets.CSPF_REPO_READ_PAT}}"}}'
        run: composer update

      - name: Shutdown default MySQL
        run: sudo service mysql stop || echo "MySQL not installed"

      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: 'password'

      - name: Install test dependencies
        if: ${{ fromJson(vars.WP_VERSIONS)[0] && matrix.wp }} # At least one WP to be tested (`nightly` excluded).
        run: composer run install:wp -- --version "${{ matrix.wp }}" --host "127.0.0.1:3306"

      - name: Run tests
        run: composer test
